-- CREATE A USER WITH CONDITIONS;
-- PASSWORD + ALL PRIVILEGES AND SHOW IT;

CREATE USER IF NOT EXISTS 'user_0d_1'@'localhost' IDENTIFIED BY 'user_0d_1_pwd';
GRANT ALL PRIVILEGES ON *.* TO 'user_0d_1'@'localhost';
SHOW GRANTS FOR 'user_0d_1'@'localhost';
